[package]
name = "hexagon2"
version = "0.0.1"
authors = ["Josh Cole"]
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"

[profile.release]
opt-level = 3
panic = 'abort'
incremental = false

[dependencies]
teensycore = { path = "../teensycore" }